service:
  name: react-stripe-subscriptions-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  createCustomer:
    handler: handler.createCustomer
    events:
      - http:
          method: post
          path: create-customer
          cors: true
